apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: app-storage
  name: app-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
